services:
  website:
    container_name: website
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - ${NEXT_APP_WEBSITE_IMAGE}
    image: ${NEXT_APP_WEBSITE_IMAGE}
    ports:
      - '3000:3000'

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
      cache_from:
        - 'ghcr.io/vergilmariy/nginx:main'
    image: 'ghcr.io/vergilmariy/nginx:main'
    ports:
      - '80:80'
      - '443:443'
    volumes: 
      - /home/ubuntu/project/cert:/etc/nginx/ssl
#    restart: always
    depends_on:
      - website
